-- Table: public.towards_ds

-- DROP TABLE public.towards_ds;

CREATE TABLE public.towards_ds
(
    title text COLLATE pg_catalog."default",
    subtitle text COLLATE pg_catalog."default",
    author text COLLATE pg_catalog."default",
    date date,
    body text COLLATE pg_catalog."default",
    link text COLLATE pg_catalog."default",
    article_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    claps bigint DEFAULT 0,
    images smallint NOT NULL DEFAULT 0,
    codeblocks smallint NOT NULL DEFAULT 0
)

TABLESPACE pg_default;

ALTER TABLE public.towards_ds
    OWNER to postgres;